/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package de.mkrane.finiteAutomataTools.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ITERATION = 1;
  /** RegularExpression Id. */
  int ALTERNATIVE = 2;
  /** RegularExpression Id. */
  int LPARAN = 3;
  /** RegularExpression Id. */
  int RPARAN = 4;
  /** RegularExpression Id. */
  int LITERAL = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"*\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "<LITERAL>",
    "<token of kind 6>",
  };

}
